# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, upload_to=b''),
        ),
    ]
