# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180725_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, max_length=3000, upload_to=b''),
        ),
    ]
